name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build Vokuro image
              run: docker build -t phalconphp/vokuro:4.1.2 -f docker/Dockerfile .
