name: Static Analysis

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
        name: Composer install
      - uses: MilesChou/composer-action@master
      - with: php-actions/composer@v5
          args: install
      - name: Phalcon action
        uses: mileschou/phalcon-action@master
        with:
          args: php vendor/bin/phpunit
